### ISSUE TITLE
按照安装流程安装后启动出错

### ISSUE THREAD

**Issue by JohnBaffin** [2kpr/ComfyUI-UltraPixel#10]
File "E:\ComfyUI-master\custom_nodes\ComfyUI-UltraPixel\nodes.py", line 4, in <module>
    from . import ultrapixel as up
  File "E:\ComfyUI-master\custom_nodes\ComfyUI-UltraPixel\ultrapixel.py", line 7, in <module>
    from .inference.utils import *
  File "E:\ComfyUI-master\custom_nodes\ComfyUI-UltraPixel\inference\utils.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

Cannot import E:\ComfyUI-master\custom_nodes\ComfyUI-UltraPixel module for custom nodes: No module named 'matplotlib'

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI-master\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: E:\ComfyUI-master\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI-master\custom_nodes\ComfyUI-Manager
   0.0 seconds (IMPORT FAILED): E:\ComfyUI-master\custom_nodes\ComfyUI-UltraPixel

**Comment by JohnBaffin** [comment]
后台安装信息：
(ComfyUI) PS E:\ComfyUI-master\custom_nodes\ComfyUI-UltraPixel> pip install -r requirements.txt
Collecting warmup-scheduler@ git+https://github.com/ildoonet/pytorch-gradual-warmup-lr.git (from -r requirements.txt (line 4))
  Cloning https://github.com/ildoonet/pytorch-gradual-warmup-lr.git to c:\users\administrator\appdata\local\temp\pip-install-3rsqs3dc\warmup-scheduler_ce69157269da460c9fbcef43c97262d4
  Running command git clone --filter=blob:none --quiet https://github.com/ildoonet/pytorch-gradual-warmup-lr.git 'C:\Users\Administrator\AppData\Local\Temp\pip-install-3rsqs3dc\warmup-scheduler_ce69157269da460c9fbcef43c97262d4'
  Resolved https://github.com/ildoonet/pytorch-gradual-warmup-lr.git to commit 6b5e8953a80aef5b324104dc0c2e9b8c34d622bd
  Preparing metadata (setup.py) ... done
Collecting torchtools@ git+https://github.com/pabloppp/pytorch-tools (from -r requirements.txt (line 5))
  Cloning https://github.com/pabloppp/pytorch-tools to c:\users\administrator\appdata\local\temp\pip-install-3rsqs3dc\torchtools_522eed3d705f48b7b22f86f0623048e2
  Running command git clone --filter=blob:none --quiet https://github.com/pabloppp/pytorch-tools 'C:\Users\Administrator\AppData\Local\Temp\pip-install-3rsqs3dc\torchtools_522eed3d705f48b7b22f86f0623048e2'
  Resolved https://github.com/pabloppp/pytorch-tools to commit 6472bd5e223142bfbe105e2006432252f1ce3709
  Preparing metadata (setup.py) ... done
Requirement already satisfied: webdataset>=0.2.79 in d:\anaconda3\envs\comfyui\lib\site-packages (from -r requirements.txt (line 1)) (0.2.86)
Requirement already satisfied: wandb>=0.16.2 in d:\anaconda3\envs\comfyui\lib\site-packages (from -r requirements.txt (line 2)) (0.17.4)
Requirement already satisfied: munch>=4.0.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from -r requirements.txt (line 3)) (4.0.0)
Requirement already satisfied: braceexpand in d:\anaconda3\envs\comfyui\lib\site-packages (from webdataset>=0.2.79->-r requirements.txt (line 1)) (0.1.7)
Requirement already satisfied: numpy in d:\anaconda3\envs\comfyui\lib\site-packages (from webdataset>=0.2.79->-r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: pyyaml in d:\anaconda3\envs\comfyui\lib\site-packages (from webdataset>=0.2.79->-r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: click!=8.0.0,>=7.1 in d:\anaconda3\envs\comfyui\lib\site-packages (from wandb>=0.16.2->-r requirements.txt (line 2)) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from wandb>=0.16.2->-r requirements.txt (line 2)) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from wandb>=0.16.2->-r requirements.txt (line 2)) (3.1.43)
Requirement already satisfied: platformdirs in d:\anaconda3\envs\comfyui\lib\site-packages (from wandb>=0.16.2->-r requirements.txt (line 2)) (4.2.2)
Requirement already satisfied: protobuf!=4.21.0,<6,>=3.19.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from wandb>=0.16.2->-r requirements.txt (line 2)) (5.27.2)
Requirement already satisfied: psutil>=5.0.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from wandb>=0.16.2->-r requirements.txt (line 2)) (6.0.0)
Requirement already satisfied: requests<3,>=2.0.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from wandb>=0.16.2->-r requirements.txt (line 2)) (2.32.3)
Requirement already satisfied: sentry-sdk>=1.0.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from wandb>=0.16.2->-r requirements.txt (line 2)) (2.10.0)
Requirement already satisfied: setproctitle in d:\anaconda3\envs\comfyui\lib\site-packages (from wandb>=0.16.2->-r requirements.txt (line 2)) (1.3.3)
Requirement already satisfied: setuptools in d:\anaconda3\envs\comfyui\lib\site-packages (from wandb>=0.16.2->-r requirements.txt (line 2)) (69.5.1)
Requirement already satisfied: torch>=1.6 in d:\anaconda3\envs\comfyui\lib\site-packages (from torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (2.3.1+cu121)
Requirement already satisfied: torchvision in d:\anaconda3\envs\comfyui\lib\site-packages (from torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (0.18.1+cu121)
Requirement already satisfied: ninja>=1.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (1.11.1.1)
Requirement already satisfied: colorama in d:\anaconda3\envs\comfyui\lib\site-packages (from click!=8.0.0,>=7.1->wandb>=0.16.2->-r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: six>=1.4.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from docker-pycreds>=0.4.0->wandb>=0.16.2->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\anaconda3\envs\comfyui\lib\site-packages (from gitpython!=3.1.29,>=1.0.0->wandb>=0.16.2->-r requirements.txt (line 2)) (4.0.11)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda3\envs\comfyui\lib\site-packages (from requests<3,>=2.0.0->wandb>=0.16.2->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\envs\comfyui\lib\site-packages (from requests<3,>=2.0.0->wandb>=0.16.2->-r requirements.txt (line 2)) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda3\envs\comfyui\lib\site-packages (from requests<3,>=2.0.0->wandb>=0.16.2->-r requirements.txt (line 2)) (1.26.19)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\envs\comfyui\lib\site-packages (from requests<3,>=2.0.0->wandb>=0.16.2->-r requirements.txt (line 2)) (2024.7.4)
Requirement already satisfied: filelock in d:\anaconda3\envs\comfyui\lib\site-packages (from torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (4.12.2)
Requirement already satisfied: sympy in d:\anaconda3\envs\comfyui\lib\site-packages (from torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (1.13.0)
Requirement already satisfied: networkx in d:\anaconda3\envs\comfyui\lib\site-packages (from torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (3.3)
Requirement already satisfied: jinja2 in d:\anaconda3\envs\comfyui\lib\site-packages (from torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (3.1.4)
Requirement already satisfied: fsspec in d:\anaconda3\envs\comfyui\lib\site-packages (from torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (2024.6.1)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in d:\anaconda3\envs\comfyui\lib\site-packages (from torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (2021.4.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from torchvision->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (10.4.0)
Requirement already satisfied: smmap<6,>=3.0.1 in d:\anaconda3\envs\comfyui\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb>=0.16.2->-r requirements.txt (line 2)) (5.0.1)
Requirement already satisfied: intel-openmp==2021.* in d:\anaconda3\envs\comfyui\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (2021.4.0)
Requirement already satisfied: tbb==2021.* in d:\anaconda3\envs\comfyui\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (2021.13.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from jinja2->torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\anaconda3\envs\comfyui\lib\site-packages (from sympy->torch>=1.6->torchtools@ git+https://github.com/pabloppp/pytorch-tools->-r requirements.txt (line 5)) (1.3.0)

**Comment by 2kpr** [comment]
Ok, I updated the requirements.txt, you can 'git pull' and 'pip install -r requirements.txt' or you can just try 'pip install matplotlib' first if you want

**Comment by JohnBaffin** [comment]
It has been resolved.
Reconfigured the Visual Studio environment,
Your steps are correct
thanks.
