### ISSUE TITLE
Hardware limitations?

### ISSUE THREAD

**Issue by SilverAkcel** [2kpr/ComfyUI-UltraPixel#11]
Near infinite on 3080TI 2048x2048, any workarounds?

**Comment by 2kpr** [comment]
Just updated...

> 
> Now works (as of 7/17) with 10GB/12GB/16GB GPUs:
> 
> - 10GB GPUs work up to (about) 2048x2048 (for text2image and controlnet)
> - 12GB GPUs work up to (about) 3072x3072 (for text2image and controlnet)
> - 16GB GPUs work up to (about) 4096x4096 (for text2image) and 3840x4096 (for controlnet)
>
