### ISSUE TITLE
display card not support bf16, is old, can run this project?

### ISSUE THREAD

**Issue by wikeeyang** [2kpr/ComfyUI-UltraPixel#15]
my display card not support bf16, is old one P40 24GB, then can use other stage_b and stage_c model? for example: "stage_b_lite.safetensors", "stage_c_lite.safetensors", few month ago, I play stable-cascade on my ConmyUI is ok.

**Comment by wikeeyang** [comment]
按这配置，就是不支持 bf16 的卡就没法跑呗？？？

**Comment by 2kpr** [comment]
Well, this is setup for bf16, along with the official weights for Stable Cascade also being bf16 and the official UltraPixel implementation too being bf16.

**Comment by wikeeyang** [comment]
我看了 official UltraPixel source code and complete the test round, in the official UltraPixel, the "bf16" is the option, not the "ONLY ONE", official UltraPixel 支持 “float16/float32 ”, in the inference script you can see "--dtype', type=str, default='bf16', help=' if bf16 does not work, change it to float32" also float16.
