### ISSUE TITLE
Weird outpus

### ISSUE THREAD

**Issue by zhenyuanzhou** [2kpr/ComfyUI-UltraPixel#4]
Sorry, this may be strange, but what image I got is extraordinary.
A close-up portrait of a young woman with flawless skin, vibrant red lipstick, and wavy brown hair, wearing a vintage floral dress and standing in front of a blooming garden.
![屏幕截图 2024-07-17 015206](https://github.com/user-attachments/assets/8679f42d-8635-42bd-8def-972b186bd562)
Do you have any idea why I got an image like this? Thank you

**Comment by 2kpr** [comment]
> Sorry, this may be strange, but what image I got is extraordinary. A close-up portrait of a young woman with flawless skin, vibrant red lipstick, and wavy brown hair, wearing a vintage floral dress and standing in front of a blooming garden.
> Do you have any idea why I got an image like this? Thank you

![ss](https://github.com/user-attachments/assets/660da9e0-e078-4daf-bcac-fd17050e11b0)

I used the same inputs as you and I got this.

Maybe one of the downloaded files got corrupted slightly in transit?
What GPU are you using?

Here are the sha256sums:

ComfyUI/models/ultrapixel$ sha256sum *
e23c1fe17ba8cdd6c49a5b292d72502bd4cf729e7de9f2060bb4dcc26737c0a0  effnet_encoder.safetensors
7d66285b840aaaf69abe809727f0b02657c513dd9376f2f07f3c3ba4fe87f250  previewer.safetensors
0a3f5a0b618494f81964dc719dbaaa9bd52f207d464d5fbf45442d363e1c0b5a  stage_a.safetensors
fe92687deefcfb33bb3ec181254b55fe4e434c5084ce9d38815eaa32487ad376  stage_b_lite_bf16.safetensors
dfe24009fc881011f350d08d9d13be13a1a3b3cbfed667435efe0fd419aca099  stage_c_bf16.safetensors
bef96cabf1621405cd6fdc4ee51b3613e68dd593a4bda3306a021e085e73ee60  ultrapixel_t2i.safetensors

**Comment by zhenyuanzhou** [comment]
Thank you for the prompting response. I'm using 3080ti laptop. The downloads do being interrupted several times. I'll check my files again to make sure they are complete.

**Comment by 2kpr** [comment]
> Thank you for the prompting response. I'm using 3080ti laptop. The downloads do being interrupted several times. I'll check my files again to make sure they are complete.

Many of these generations easily get into the 16GB+ range, so not sure in the current setup that this UltraPixel will work well on that gpu, 12GB right?

![ss](https://github.com/user-attachments/assets/0932194e-078e-4e3a-ab0b-60fff55cf06e)

**Comment by zhenyuanzhou** [comment]
My VRAM is 16GB, should be enough, I have checked all the files, the sha are the same as what you provided. Just don't know what happened.

**Comment by zhenyuanzhou** [comment]
![ComfyUI_00004_](https://github.com/user-attachments/assets/e552932c-730f-43aa-8749-bcc7f7d7fef8)

Em... Why...

**Comment by zhenyuanzhou** [comment]
May I ask where I need to put this model? The program is trying to download it but is not successful. Maybe my issue is due to this
laion/CLIP-ViT-bigG-14-laion2B-39B-b160k

**Comment by 2kpr** [comment]
> May I ask where I need to put this model? The program is trying to download it but is not successful. Maybe my issue is due to this laion/CLIP-ViT-bigG-14-laion2B-39B-b160k

Yes it downloads these too:
https://github.com/2kpr/ComfyUI-UltraPixel/blob/main/train/train_t2i.py#L143-L144

I'm not sure where to put it mine just automatically downloaded using put mine here:
/home/<username>/.cache/huggingface/hub/models--laion--CLIP-ViT-bigG-14-laion2B-39B-b160k
/home/<username>/.cache/huggingface/hub/models--openai--clip-vit-large-patch14

**Comment by zhenyuanzhou** [comment]
![image](https://github.com/user-attachments/assets/7c36c1c3-aac6-4264-9eea-f7bcb23c161f)
Fixed after re-download the two model
